spring.config.import=optional:file:.env[.properties]
spring.application.name=foodzie
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=10

server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=Strict
server.servlet.session.cookie.domain=localhost

spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.security.user.name= ${SPRING_SECURITY_USERNAME}
#spring.security.user.password= ${SPRING_SECURITY_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000
jwt.refresh-token-expiry-ms=604800000

app.client.url=${APP_CLIENT_URL}